# Constants to be used in Haptic Midi projects

# defines the start of numberring of the channels
# user should change it, default is 10 now
MHP_CHAN_BASE=10

# channel offsets added to the start of numberring
MHP_CHANOFFSET_RH=0
MHP_CHANOFFSET_LH=1
MHP_RH_CHAN=MHP_CHAN_BASE + MHP_CHANOFFSET_RH
MHP_LH_CHAN=MHP_CHAN_BASE + MHP_CHANOFFSET_LH

# note letter to offset from octave base
NOTE_C =0
NOTE_CS=1 # C-sharp  
NOTE_DF=1 # D-flat  
NOTE_D =2
NOTE_DS=3 # D-sharp  
NOTE_EF=3 # E-flat 
NOTE_E =4
NOTE_F=5 
NOTE_FS=6 
NOTE_GF=6 
NOTE_G=7
NOTE_GS=8 
NOTE_AF=8
NOTE_A=9
NOTE_AS=10
NOTE_BF=10
NOTE_B=11
 
# note base number for each octave
OCTAVE_m1= 0
OCTAVE_0=  12 
OCTAVE_1=  24
OCTAVE_2=  36
OCTAVE_3=  48
OCTAVE_4=  60  
OCTAVE_5=  72  
OCTAVE_6=  84  
OCTAVE_7=  96  
OCTAVE_8=  108  
OCTAVE_9=  120 # not full up to G9 

# octave for each action for given finger name
MHP_ACT_THB= OCTAVE_1
MHP_ACT_IND= OCTAVE_2
MHP_ACT_MID= OCTAVE_3
MHP_ACT_RNG= OCTAVE_4
MHP_ACT_PKY= OCTAVE_5

# octave for each action for given finger number
MHP_ACT_1= OCTAVE_1
MHP_ACT_2= OCTAVE_2
MHP_ACT_3= OCTAVE_3
MHP_ACT_4= OCTAVE_4
MHP_ACT_5= OCTAVE_5

# action mode FLX is Flex, EXT is Extension, IMP is Impulsion
MHP_ACT_FLX= NOTE_F
MHP_ACT_EXT= NOTE_E
MHP_ACT_IMP= NOTE_A

# control number for each angle
MHP_STA_LSB_OFFSET=  32
MHP_STA_THBR= 20
MHP_STA_THBR2= MHP_STA_THBR + MHP_STA_LSB_OFFSET
MHP_STA_THBS= 21
MHP_STA_THBS2= MHP_STA_THBS + MHP_STA_LSB_OFFSET
MHP_STA_THBB= 22
MHP_STA_THBB2= MHP_STA_THBB + MHP_STA_LSB_OFFSET

MHP_STA_INDS= 23
MHP_STA_INDS2= MHP_STA_INDS + MHP_STA_LSB_OFFSET
MHP_STA_INDB= 24
MHP_STA_INDB2= MHP_STA_INDB + MHP_STA_LSB_OFFSET

MHP_STA_MIDS= 25
MHP_STA_MIDS2= MHP_STA_MIDS + MHP_STA_LSB_OFFSET
MHP_STA_MIDB= 26
MHP_STA_MIDB2= MHP_STA_MIDB + MHP_STA_LSB_OFFSET

MHP_STA_RNGS= 27
MHP_STA_RNGS2= MHP_STA_RNGS + MHP_STA_LSB_OFFSET
MHP_STA_RNGB= 28
MHP_STA_RNGB2= MHP_STA_RNGB + MHP_STA_LSB_OFFSET

MHP_STA_PKYS= 29
MHP_STA_PKYS2= MHP_STA_PKYS + MHP_STA_LSB_OFFSET
MHP_STA_PKYB= 30
MHP_STA_PKYB2= MHP_STA_PKYB + MHP_STA_LSB_OFFSET
